[book]
authors = ["hengfeiyang"]
language = "zh-CN"
multilingual = false
src = "docs"
title = "How Query Engines Work 中文版"

[output.html]
git-repository-url = "https://github.com/hengfeiyang/how-query-engines-work-zh-CN"
edit-url-template = "https://github.com/hengfeiyang/how-query-engines-work-zh-CN/edit/main/{path}"
